/// Template Engine & Project Generation Core library for Flutter Package Studio.
library;

export 'template_manifest.dart';
export 'template_model.dart';
export 'template_registry.dart';
export 'template_context.dart';
export 'template_renderer.dart';
export 'template_condition.dart';
export 'generation_plan.dart';
export 'generation_result.dart';
export 'project_generator.dart';
export 'builtin_templates.dart';
export 'template_semver.dart';
export 'template_dependency.dart';
export 'template_capabilities.dart';
export 'template_compatibility.dart';
export 'resolved_template.dart';
export 'template_composition.dart';
export 'template_resolver.dart';
export 'composition/composition.dart';
export 'customization/customization.dart';
export 'quality/quality.dart';
export 'hooks/hooks.dart';
export 'certification/certification.dart';
export 'testing/testing.dart';
export '../testing/project/project.dart';
export '../testing/unit/unit.dart';
export '../testing/widget/widget.dart';
export '../testing/integration/integration.dart';
export '../testing/fixtures/fixtures.dart';
export '../testing/runner/runner.dart';
export 'migration/migration.dart';

export '../documentation/readme/readme.dart';
export '../documentation/api/api.dart';
export '../documentation/architecture/architecture.dart';
export '../documentation/mermaid/mermaid.dart';
export '../documentation/examples/examples.dart';
export '../documentation/screenshots/screenshots.dart';
export '../documentation/gifs/gifs.dart';
export '../documentation/website/website.dart';
export '../compatibility/compatibility.dart';
