/// AI Assistant Core Foundation library for Flutter Package Studio (Milestone 8).
library;

export 'provider/ai_provider.dart';
export 'provider/mock_ai_provider.dart';
export 'models/assistant_models.dart';
export 'engine/assistant_engine.dart';
export 'renderer/assistant_renderer.dart';
export 'context/project_context_models.dart';
export 'context/sensitive_file_filter.dart';
export 'context/project_context_engine.dart';
export 'context/project_context_renderer.dart';
export 'review/code_review_models.dart';
export 'review/code_review_engine.dart';
export 'review/code_review_renderer.dart';
export 'testing/test_intelligence_models.dart';
export 'testing/test_intelligence_engine.dart';
export 'testing/test_intelligence_renderer.dart';
export 'diagnosis/failure_diagnosis_models.dart';
export 'diagnosis/failure_diagnosis_engine.dart';
export 'diagnosis/failure_diagnosis_renderer.dart';
export 'architecture/architecture_models.dart';
export 'architecture/architecture_advisor_engine.dart';
export 'architecture/architecture_advisor_renderer.dart';
export 'documentation/documentation_models.dart';
export 'documentation/documentation_assistant_engine.dart';
export 'documentation/documentation_assistant_renderer.dart';
export 'dependencies/dependency_models.dart';
export 'dependencies/dependency_advisor_engine.dart';
export 'dependencies/dependency_advisor_renderer.dart';
export 'security/secret_redactor.dart';
export 'security/security_models.dart';
export 'security/security_advisor_engine.dart';
export 'security/security_advisor_renderer.dart';
export 'release/release_readiness_models.dart';
export 'release/release_readiness_advisor_engine.dart';
export 'release/release_readiness_renderer.dart';
export 'planner/workflow_planner_models.dart';
export 'planner/workflow_planner_engine.dart';
export 'planner/workflow_planner_renderer.dart';

