/// Central Code Generation Engine for Phase 10.8.
library;

import 'package:syntrix/src/logging/logger.dart';
import 'package:syntrix/src/studio_v2/studio_v2_models.dart';
import 'package:syntrix/src/studio_v2/codegen/studio_codegen_models.dart';
import 'package:syntrix/src/studio_v2/scene/studio_scene_models.dart';

/// Central Code Generation Engine converting Studio v2 configurations into production Flutter code.
class StudioCodeGenEngine {
  final Logger _logger = Logger('StudioCodeGenEngine');

  /// Set of verified public API identifiers.
  static const Set<String> _validPublicLoaders = {
    'infinite_universe',
    'galaxy_orbit',
    'nebula_storm',
    'quantum_void',
    'pulsar_wave',
    'cyber_matrix',
  };

  static const Set<String> _validPublicThemes = {
    'deep_space',
    'milky_way',
    'nebula_storm',
    'quantum_void',
    'solar_flare',
    'cyber_galaxy',
    'aurora_cosmos',
  };

  /// Generate production-ready Flutter code from a [StudioConfigurationDescriptor].
  CodeGenResult generateLoaderCode(
    StudioConfigurationDescriptor config, {
    CodeGenOptions options = const CodeGenOptions(),
  }) {
    _logger.info(
        'Generating Flutter code for loader "${config.targetLoaderId}" (Style: ${options.style.id})');

    final warnings = <String>[];
    final isValidLoader = _validPublicLoaders.contains(config.targetLoaderId);
    final isValidTheme = _validPublicThemes.contains(config.selectedThemeId);

    if (!isValidLoader) {
      warnings.add(
          'Loader "${config.targetLoaderId}" is not a recognized built-in public loader API.');
    }
    if (!isValidTheme) {
      warnings.add(
          'Theme "${config.selectedThemeId}" is custom or not in built-in theme presets.');
    }

    final buffer = StringBuffer();
    final requiredImports = <String>['package:flutter/material.dart'];

    if (options.includeImports) {
      for (final imp in requiredImports) {
        buffer.writeln('import \'$imp\';');
      }
      buffer.writeln();
    }

    if (options.includeComments) {
      buffer
          .writeln('// Generated by Syntrix Studio v2 Code Generation Engine');
      buffer.writeln(
          '// Target Loader: ${config.targetLoaderId} | Theme: ${config.selectedThemeId}');
      buffer.writeln('// Production-ready, zero-private API leak guarantee.');
      buffer.writeln();
    }

    final loaderWidgetCode = _buildLoaderInvocation(config);

    switch (options.style) {
      case CodeGenStyle.standaloneWidget:
        buffer.writeln('Widget build${_pascalCase(config.targetLoaderId)}() {');
        buffer
            .writeln('  return ${_wrapContainer(loaderWidgetCode, options)};');
        buffer.writeln('}');
        break;

      case CodeGenStyle.statelessWidgetClass:
        buffer.writeln(
            'class ${options.customClassName} extends StatelessWidget {');
        buffer.writeln('  const ${options.customClassName}({super.key});');
        buffer.writeln();
        buffer.writeln('  @override');
        buffer.writeln('  Widget build(BuildContext context) {');
        buffer.writeln(
            '    return ${_wrapContainer(loaderWidgetCode, options)};');
        buffer.writeln('  }');
        buffer.writeln('}');
        break;

      case CodeGenStyle.statefulInteractiveWidget:
        buffer.writeln(
            'class ${options.customClassName} extends StatefulWidget {');
        buffer.writeln('  const ${options.customClassName}({super.key});');
        buffer.writeln();
        buffer.writeln('  @override');
        buffer.writeln(
            '  State<${options.customClassName}> createState() => _${options.customClassName}State();');
        buffer.writeln('}');
        buffer.writeln();
        buffer.writeln(
            'class _${options.customClassName}State extends State<${options.customClassName}> {');
        buffer.writeln('  double _speed = ${config.animationSpeed};');
        buffer.writeln('  int _particleCount = ${config.particleCount};');
        buffer.writeln();
        buffer.writeln('  @override');
        buffer.writeln('  Widget build(BuildContext context) {');
        buffer.writeln(
            '    return ${_wrapContainer(loaderWidgetCode, options)};');
        buffer.writeln('  }');
        buffer.writeln('}');
        break;

      case CodeGenStyle.configurationSnippet:
        buffer.writeln(loaderWidgetCode);
        break;

      case CodeGenStyle.sceneStackWidget:
        buffer.writeln('Widget buildSceneStack() {');
        buffer
            .writeln('  return ${_wrapContainer(loaderWidgetCode, options)};');
        buffer.writeln('}');
        break;
    }

    return CodeGenResult(
      sourceCode: buffer.toString(),
      options: options,
      isValidPublicApi: isValidLoader && isValidTheme,
      requiredImports: requiredImports,
      warnings: warnings,
      generatedAt: DateTime.now(),
    );
  }

  /// Generate composite scene stack code.
  CodeGenResult generateSceneCode(
    VisualSceneDescriptor scene, {
    CodeGenOptions options = const CodeGenOptions(),
  }) {
    _logger.info('Generating scene code for "${scene.name}"');

    final buffer = StringBuffer();
    final requiredImports = <String>['package:flutter/material.dart'];

    if (options.includeImports) {
      buffer.writeln('import \'package:flutter/material.dart\';');
      buffer.writeln();
    }

    if (options.includeComments) {
      buffer.writeln('// Composite Scene generated by Syntrix Studio v2');
      buffer.writeln('// Scene: ${scene.name} (${scene.layers.length} layers)');
      buffer.writeln();
    }

    buffer.writeln(
        'class ${options.customClassName}Scene extends StatelessWidget {');
    buffer.writeln('  const ${options.customClassName}Scene({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) {');
    buffer.writeln('    return SizedBox(');
    buffer.writeln('      width: ${scene.width},');
    buffer.writeln('      height: ${scene.height},');
    buffer.writeln('      child: Stack(');
    buffer.writeln('        children: [');

    for (final layer in scene.layers.where((l) => l.isVisible)) {
      buffer.writeln(
          '          // ${layer.name} (${layer.layerType.displayName})');
      buffer.writeln('          Opacity(');
      buffer.writeln('            opacity: ${layer.opacity},');
      buffer.writeln('            child: SceneLayerComponent(');
      buffer.writeln('              layerId: \'${layer.layerId}\',');
      buffer
          .writeln('              reference: \'${layer.componentReference}\',');
      buffer.writeln('            ),');
      buffer.writeln('          ),');
    }

    buffer.writeln('        ],');
    buffer.writeln('      ),');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');

    return CodeGenResult(
      sourceCode: buffer.toString(),
      options: options,
      isValidPublicApi: true,
      requiredImports: requiredImports,
      generatedAt: DateTime.now(),
    );
  }

  String _buildLoaderInvocation(StudioConfigurationDescriptor config) {
    final buffer = StringBuffer();
    final loaderClass = '${_pascalCase(config.targetLoaderId)}Loader';
    final themeEnum = 'UniverseTheme.${_camelCase(config.selectedThemeId)}';

    buffer.writeln('$loaderClass(');
    buffer.writeln('  theme: $themeEnum,');
    buffer.writeln('  animationSpeed: ${config.animationSpeed},');
    buffer.writeln('  intensity: ${config.intensity},');
    buffer.writeln('  scale: ${config.scale},');
    buffer.writeln('  particleCount: ${config.particleCount},');
    buffer.writeln('  particleSize: ${config.particleSize},');
    buffer.writeln('  particleOpacity: ${config.particleOpacity},');
    buffer.writeln('  gravity: ${config.gravity},');
    buffer.writeln('  velocity: ${config.velocity},');
    buffer.writeln('  isInteractive: ${config.isInteractive},');
    buffer.writeln('  shadersEnabled: ${config.shadersEnabled},');
    buffer.write(')');

    return buffer.toString();
  }

  String _wrapContainer(String childCode, CodeGenOptions options) {
    if (options.wrapWithCenter) {
      return 'Center(\n    child: $childCode,\n  )';
    }
    return childCode;
  }

  static String _pascalCase(String text) {
    return text
        .split('_')
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join('');
  }

  static String _camelCase(String text) {
    final pascal = _pascalCase(text);
    if (pascal.isEmpty) return '';
    return pascal[0].toLowerCase() + pascal.substring(1);
  }
}
