/// Domain models for Phase 9.6: Enterprise Dependency Governance.
library;

/// Classification status of a dependency.
enum DependencyGovernanceStatus {
  approved,
  restricted,
  blocked,
  unclassified,
  vulnerable,
  outdated,
  licenseViolation;

  String get label => name.toUpperCase();
}

/// Type of dependency relationship.
enum DependencyType {
  direct,
  dev,
  transitive,
  override;

  String get id => name;
}

/// Finding generated by dependency governance analysis.
class DependencyGovernanceFinding {
  final String packageName;
  final String declaredVersion;
  final DependencyType dependencyType;
  final DependencyGovernanceStatus status;
  final String reason;
  final String? license;
  final String? advisoryId;
  final String? recommendation;
  final bool isBlocking;

  const DependencyGovernanceFinding({
    required this.packageName,
    required this.declaredVersion,
    required this.dependencyType,
    required this.status,
    required this.reason,
    this.license,
    this.advisoryId,
    this.recommendation,
    this.isBlocking = false,
  });

  Map<String, dynamic> toJson() => {
        'package_name': packageName,
        'declared_version': declaredVersion,
        'dependency_type': dependencyType.id,
        'status': status.name,
        'reason': reason,
        'license': license,
        'advisory_id': advisoryId,
        'recommendation': recommendation,
        'is_blocking': isBlocking,
      };

  factory DependencyGovernanceFinding.fromJson(Map<String, dynamic> json) {
    return DependencyGovernanceFinding(
      packageName: json['package_name'] as String? ?? 'unknown',
      declaredVersion: json['declared_version'] as String? ?? 'any',
      dependencyType: DependencyType.values.firstWhere(
        (t) => t.name == json['dependency_type'],
        orElse: () => DependencyType.direct,
      ),
      status: DependencyGovernanceStatus.values.firstWhere(
        (s) => s.name == json['status'],
        orElse: () => DependencyGovernanceStatus.unclassified,
      ),
      reason: json['reason'] as String? ?? '',
      license: json['license'] as String?,
      advisoryId: json['advisory_id'] as String?,
      recommendation: json['recommendation'] as String?,
      isBlocking: json['is_blocking'] as bool? ?? false,
    );
  }
}

/// Comprehensive dependency governance policy definition.
class EnterpriseDependencyPolicy {
  final List<String> approvedPackages;
  final List<String> restrictedPackages;
  final List<String> blockedPackages;
  final List<String> allowedLicenses;
  final List<String> blockedLicenses;
  final bool blockUnapprovedPackages;
  final bool blockGitDependencies;
  final bool blockPathDependencies;
  final bool blockKnownVulnerabilities;

  const EnterpriseDependencyPolicy({
    this.approvedPackages = const [
      'flutter',
      'flutter_test',
      'http',
      'path',
      'meta',
      'collection'
    ],
    this.restrictedPackages = const [],
    this.blockedPackages = const [],
    this.allowedLicenses = const [
      'MIT',
      'Apache-2.0',
      'BSD-3-Clause',
      'BSD-2-Clause',
      'ISC'
    ],
    this.blockedLicenses = const ['GPL-3.0', 'AGPL-3.0', 'SSPL'],
    this.blockUnapprovedPackages = false,
    this.blockGitDependencies = true,
    this.blockPathDependencies = true,
    this.blockKnownVulnerabilities = true,
  });

  Map<String, dynamic> toJson() => {
        'approved_packages': approvedPackages,
        'restricted_packages': restrictedPackages,
        'blocked_packages': blockedPackages,
        'allowed_licenses': allowedLicenses,
        'blocked_licenses': blockedLicenses,
        'block_unapproved_packages': blockUnapprovedPackages,
        'block_git_dependencies': blockGitDependencies,
        'block_path_dependencies': blockPathDependencies,
        'block_known_vulnerabilities': blockKnownVulnerabilities,
      };

  factory EnterpriseDependencyPolicy.fromJson(Map<String, dynamic> json) {
    return EnterpriseDependencyPolicy(
      approvedPackages: (json['approved_packages'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
      restrictedPackages: (json['restricted_packages'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
      blockedPackages: (json['blocked_packages'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
      allowedLicenses: (json['allowed_licenses'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const ['MIT', 'Apache-2.0', 'BSD-3-Clause', 'BSD-2-Clause', 'ISC'],
      blockedLicenses: (json['blocked_licenses'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const ['GPL-3.0', 'AGPL-3.0', 'SSPL'],
      blockUnapprovedPackages:
          json['block_unapproved_packages'] as bool? ?? false,
      blockGitDependencies: json['block_git_dependencies'] as bool? ?? true,
      blockPathDependencies: json['block_path_dependencies'] as bool? ?? true,
      blockKnownVulnerabilities:
          json['block_known_vulnerabilities'] as bool? ?? true,
    );
  }
}

/// Result of evaluating dependencies against enterprise governance policy.
class DependencyGovernanceResult {
  final bool isCompliant;
  final bool isBlocked;
  final String targetPackageName;
  final int totalDependenciesAnalyzed;
  final List<DependencyGovernanceFinding> findings;
  final int approvedCount;
  final int restrictedCount;
  final int blockedCount;
  final int vulnerableCount;
  final int licenseViolationCount;
  final String summary;
  final int durationMs;
  final DateTime timestamp;

  const DependencyGovernanceResult({
    required this.isCompliant,
    required this.isBlocked,
    required this.targetPackageName,
    required this.totalDependenciesAnalyzed,
    required this.findings,
    required this.approvedCount,
    required this.restrictedCount,
    required this.blockedCount,
    required this.vulnerableCount,
    required this.licenseViolationCount,
    required this.summary,
    required this.durationMs,
    required this.timestamp,
  });

  Map<String, dynamic> toJson() => {
        'is_compliant': isCompliant,
        'is_blocked': isBlocked,
        'target_package_name': targetPackageName,
        'total_dependencies_analyzed': totalDependenciesAnalyzed,
        'findings': findings.map((f) => f.toJson()).toList(),
        'approved_count': approvedCount,
        'restricted_count': restrictedCount,
        'blocked_count': blockedCount,
        'vulnerable_count': vulnerableCount,
        'license_violation_count': licenseViolationCount,
        'summary': summary,
        'duration_ms': durationMs,
        'timestamp': timestamp.toIso8601String(),
      };

  factory DependencyGovernanceResult.fromJson(Map<String, dynamic> json) {
    return DependencyGovernanceResult(
      isCompliant: json['is_compliant'] as bool? ?? false,
      isBlocked: json['is_blocked'] as bool? ?? true,
      targetPackageName: json['target_package_name'] as String? ?? 'unknown',
      totalDependenciesAnalyzed:
          json['total_dependencies_analyzed'] as int? ?? 0,
      findings: (json['findings'] as List<dynamic>?)
              ?.map((f) => DependencyGovernanceFinding.fromJson(
                  f as Map<String, dynamic>))
              .toList() ??
          const [],
      approvedCount: json['approved_count'] as int? ?? 0,
      restrictedCount: json['restricted_count'] as int? ?? 0,
      blockedCount: json['blocked_count'] as int? ?? 0,
      vulnerableCount: json['vulnerable_count'] as int? ?? 0,
      licenseViolationCount: json['license_violation_count'] as int? ?? 0,
      summary: json['summary'] as String? ?? '',
      durationMs: json['duration_ms'] as int? ?? 0,
      timestamp: json['timestamp'] is String
          ? DateTime.parse(json['timestamp'] as String)
          : DateTime.now(),
    );
  }
}
